Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora33"
  config.vm.hostname = "fedora33"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.provision "shell", inline: <<-SHELL
    rm -rf /home/vagrant/app
    mkdir -p /home/vagrant/app
  SHELL
#   config.vm.provision "file", source: "Dockerfile", destination: "/tmp/"
#   config.vm.provision "file", source: "custom-endpoints/target/custom-endpoints-1.0.0-SNAPSHOT.jar", destination: "/tmp/"

  config.vm.provision "shell", inline: <<-SHELL
#     cp /tmp/Dockerfile /tmp/custom-endpoints-1.0.0-SNAPSHOT.jar /home/vagrant/app/
    chown -R vagrant /home/vagrant/app/
    yum install -y podman
    groupadd -f -r podman

#     usermod -aG podman $SUDO_USER
    mkdir -p /etc/systemd/system/podman.socket.d
    cat >/etc/systemd/system/podman.socket.d/override.conf <<EOF
[Socket]
SocketMode=0660
SocketUser=root
SocketGroup=podman
EOF
    systemctl daemon-reload
    echo "d /run/podman 0770 root podman" > /etc/tmpfiles.d/podman.conf
    sudo systemd-tmpfiles --create

    systemctl enable podman.socket
    systemctl start podman.socket

    usermod -aG podman $SUDO_USER
  SHELL
end
