@Library('shared-jenkins-library') _
node {
        //   stage('checkout repo from Git')
        //   {
            //   checkout scm
            // checkout([$class: 'GitSCM', branches: [[name: '*/zvikatest']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/RHEcosystemAppEng/rhpam-deployment']]])
    
        //   }
    
        stage('Authentication To AWS') {
                
                withCredentials([usernamePassword(credentialsId: 'AWS_CREDENTIALS', passwordVariable: 'PASSWORD', usernameVariable: 'USER')]) {
                     authenticateAWS (USER, PASSWORD, 'us-east-1')
                 }
                 
        }
        
        stage('fetching instance by tag')
        {
            sh 'aws ec2 describe-tags --filters Name=resource-type,Values=instance Name=tag:app,Values=RHPAM-KS'
            sh 'aws ec2 describe-instances --instance-ids i-0552fc879804aaf8d'
            // getAwsInstanceByAppTagValue("RHPAM-KS")
        }
        // stage('Deploy to KIeServer') {
        //       try{ 
        //         withCredentials([usernamePassword(credentialsId: 'KS_CREDENTIALS', passwordVariable: 'PASSWORD', usernameVariable: 'USER')]) {
        //              deployToKieServerArtifact ("44.201.138.226:8080",USER, PASSWORD,"test_1.0.0-SNAPSHOT", 'com.myspace',"test","1.0.0-SNAPSHOT")
        //         }
        //       }
        //         catch(Exception)
        //         {
        //          echo "Failed to deploy artifact"   
        //         }
                                  
                
        //     }
            
        stage('Clean Workspace')
          {
              cleanWs()
          }
}
