apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: custom-rhpam-mssql
spec:
  environment: rhpam-production
  commonConfig:
    adminPassword: password
    adminUser: admin
    amqClusterPassword: password
    amqPassword: password
    dbPassword: password
    keyStorePassword: password
    applicationName: custom-rhpam-mssql
  objects:
    console:
      keystoreSecret: businesscentral-app-secret
      replicas: 1
    servers:
      - build:
          extensionImageStreamTag: jboss-kie-mssql-extension-openshift-image:7.2.2.jre11
          extensionImageStreamTagNamespace: dmartino-mssql
        database:
          type: external
          externalConfig:
            extensionImage: true
            driver: mssql
            dialect: org.hibernate.dialect.SQLServer2012Dialect
            jdbcURL: jdbc:sqlserver://172.30.23.105:31433;DatabaseName=rhpam
            nonXA: 'true'
            username: sa
            password: msSql2019
            minPoolSize: '10'
            maxPoolSize: '10'
            connectionChecker: >-
              org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
            exceptionSorter: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLExceptionSorter
            backgroundValidation: "true"
        image: rhpam-kieserver-rhel8-custom
        imageContext: dmartino-mssql
        imageTag: '7.11.0-4'
        id: kieserver-1
        keystoreSecret: kieserver-app-secret
        name: custom-kieserver
        replicas: 1
    smartRouter:
      keystoreSecret: smartrouter-app-secret